export const animals = {
    crocodiles: {
      image: './images/saltwater-croc.png',
      facts: ["Saltwater crocodiles are the largest crocodile species in the world, and the largest living reptile in the world.", "Male saltwater crocodiles have been recorded at lengths of 23 feet (7 m) and weights of 2,205 pounds (1,000 kg). Females are much smaller, growing to be about 10 feet (3 m) long and weighing 330 pounds (150 kg).", "Adult saltwater crocodiles have 66 teeth on average and the greatest bite pressure of any animal in the world.", "Saltwater crocodiles are most commonly found in coastal waters or rivers where they can swim between freshwater and brackish water.", "Saltwater crocodiles can live more than 70 years.", "Saltwater crocodiles are opportunistic feeders that prey on a variety of species, from crabs and fish to birds, turtles, pigs, buffalo and even humans.","Saltwater crocodiles communicate using several sounds, including barking, hissing, growling and chirps.", "These reptiles possess the strongest bite force of any living animal, with a bite force of approximately 3,700 pounds. Their attacks are rarely survivable."]
    },
    elephant: {
      image: './images/polar-bear.png',
      facts: ["The African Savanna (Bush) elephant is the world's largest land animal – with adult males, or bull elephants, standing up to 3m high and weighing up to 6,000kg on average. Males only reach their full size at 35-40 years - that’s well over half their lifespan as wild elephants can live for up to 60-70 years. And it’s not just the adults – even calves are huge! At birth, a baby elephant can weigh 120kg - that’s almost 19 stone.", "There are three species of elephant: African Savanna (Bush), African Forest and Asian. The ears of African elephants are much larger than their cousins and are described as being shaped like the African continent, whereas the ears of Asian elephants are shaped like the Indian subcontinent. There’s also a trunk difference - African elephants have two ‘fingers’ at the tip of their trunks, whereas Asian elephants have one.", "Elephants have around 150,000 muscle units in their trunk. Their trunks are perhaps the most sensitive organ found in any mammal. Elephants use their trunks to suck up water to drink – it can contain up to 8 litres of water. They also use their trunks as a snorkel when swimming.", "Elephant tusks are actually enlarged incisor teeth which first appear when elephants are around 2 years old. Tusks continue growing throughout their lives. Tusks are used to help with feeding - prising bark off trees or digging up roots - or as a defence when fighting. But these beautiful tusks often cause elephants danger. They\'re made from ivory; a much desired object. Read on to find out why elephants are under threat.", "An elephant’s skin is 2.5cm thick in most places.  The folds and wrinkles in their skin can retain up to 10 times more water than flat skin does, which helps to cool them down. They keep their skin clean and protect themselves from sunburn by taking regular dust and mud baths.", "Elephants eat grasses, leaves, shrubs, fruits and roots depending on the season and their habitat. When it’s particularly dry, elephants will eat more woody parts of trees and shrubs like twigs, branches and barks. They need to eat up to 150kg of food per day – that's around 375 tins of baked beans – although half of this may leave the body undigested.  Elephants eat so much that they can spend up to three-quarters of their day just eating."]
    },
    hippo: {
      image: './image/hippo.png',
      facts: ["Despite their large size and often comical appearance, hippos are incredibly aggressive and territorial. They are known for charging boats and attacking anyone who enters their territory. ", "They are considered the second largest land animal on Earth (first place goes to the elephant!). Males measure around 3.5m long and 1.5m tall, and can weigh up 3,200kg. That’s as much as three small cars!", "To stay cool in the blistering African heat, hippos spend most of their day in rivers and lakes. Their eyes, nose and ears are located on the top of their head, which means they can see and breathe whilst submerged in the water. What’s more, these super-cool creatures sweat an oily red liquid which helps protect their skin from drying out – and acts as a sunblock, too! Cool, huh?", "These magnificent mammals were once found throughout all sub-saharan Africa. Sadly, populations have declined due to habitat loss and hunting. Today, they are largely confined to protected areas in East African countries.", "Hippos are most active at night, when they forage for food. They are herbivores, and eat mostly grass – and boy do they eat grass! In just one night, they can guzzle down up to 35kg of their favourite grub!", "Despite their enormous size, hippos are great swimmers and can hold their breath for up to five minutes underwater. When completely submerged, their ears and nostrils fold shut to keep water out.", "Hippos usually live in groups (or “herds”) of around ten to 20 individuals, led by one large dominant male. The other members are females, their young and a few young non-breeding males.", "Dominant males are very protective over their group. To warn off rival males, they open their huge mouths and display their long, curved canines! They also make loud grunts and aggressive splashes in the water.", "Female hippos, called cows, give birth every two years, usually to a single calf. Soon after birth, the mother and her baby join up with other cows and calves for protection against predators, such as crocodiles, lions and hyenas.", "In the wild hippos live for around 40 years. In captivity, they tend to live longer and may reach up to 50 years old."]
    }
  };